### ISSUE TITLE
[OLD] Legacy Hungarian Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/hu.react.dev#1]
## Maintainer List

* @balazsorban44
* @gergely-nagy
* @punkah

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the [glossary](https://github.com/reactjs/hu.reactjs.org/issues/2) and [style guide](https://github.com/reactjs/hu.reactjs.org/blob/style-guide/style-guide.md) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

Optionally use one of these emojis

emoji | meaning
-- | --
👨‍🔧👩‍🔧 | Work in Progress
🧐 | In review

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page @balazsorban44 (#4)
* [x] Tutorial @balazsorban44 (#5)

### Basics

* [x] Hello World @gergely-nagy (#7)
* [x] Introducing JSX @gergely-nagy (#21)
* [x] Rendering Elements @balazsorban44 (#8)
* [x] Components and Props @balazsorban44 (#9)
* [x] State and Lifecycle @balazsorban44 (#12)
* [x] Handling Events @punkah (#37) 
* [x] Conditional Rendering @balazsorban44 (#13)
* [x] Lists and Keys @balazsorban44 (#14)
* [x] Forms @punkah (#38)
* [x] Lifting State Up @balazsorban44 (#18)
* [x] Composition vs Inheritance @balazsorban44 (#15)
* [x] Thinking in React @n3ko (#27)

### API Reference

* [x] React @balazsorban44 (#39)
* [x] React.Component @punkah (#49)
* [x] ReactDOM @balazsorban44 (#40)
* [x] ReactDOMServer @balazsorban44 (#41)
* [x] DOM Elements @balazsorban44 (#51)
* [x] SyntheticEvent @balazsorban44 (#50)
* [x] Test Utilities @balazsorban44 (#53) 
* [x] Shallow Renderer @balazsorban44 (#52) 
* [x] Test Renderer @balazsorban44 (#54)
* [x] JS Environment Requirements @balazsorban44 (#42)
* [x] Glossary @balazsorban44 (#16)

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml @balazsorban44 (#5)
* [x] docs/nav.yml @balazsorban44 (#11 )

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started @punkah (#29)
* [x] Add React to a Website @balazsorban44 (#44)
* [x] Create a New React App @balazsorban44 (#43)
* [x] CDN Links @gergely-nagy (#66) 

### Hooks

Everyone is hooked on hooks! People are really excited about these and it would be great for them to be translated.

  * [x] Introducing Hooks @balazsorban44 (#48)
  * [x] Hooks at a Glance @balazsorban44 (#57)
  * [x] Using the State Hook @punkah (#62)
  * [x] Using the Effect Hook @punkah (#68)
  * [x] Rules of Hooks @balazsorban44 (#58)
  * [x] Building Your Own Hooks @balazsorban44 (#60)
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility @punkah (WIP)
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [x] Fragments @gergely-nagy (#23)
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [x] React Without JSX @RichardOtvos (#92)
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes @gergely-nagy (#) 👨‍🔧
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX @dzsi1994 (#)
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [x] CodeEditor @balazsorban44 (#45)
* [x] CodeExample @balazsorban44 (#45)
* [x] ErrorDecoder @balazsorban44 (#45)
* [x] LayoutFooter @balazsorban44 (#45)
* [x] LayoutHeader @balazsorban44 (#45)
* [x] MarkdownPage @balazsorban44 (#45)

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by gergely-nagy** [comment]
Hi! I'd like to translate the Hello World page.

**Comment by balazsorban44** [comment]
I added you as a translator for the Hello World page. :wink:

**Comment by gergely-nagy** [comment]
I'm gonna translate the `Introducing JSX` page.

**Comment by balazsorban44** [comment]
Taking the `Rendering Elements` page.

**Comment by balazsorban44** [comment]
Taking `Components and Props` page.

**Comment by balazsorban44** [comment]
Taking the `docs/nav.yml`. I feel like it will be easier to look up the titles for each page from the navbar, then finding the page titles for each nav element afterward.

**Comment by balazsorban44** [comment]
Taking `State and Lifecycle` page.

**Comment by kadosknight** [comment]
Would translate `Handling Events` page

**Comment by gergely-nagy** [comment]
You got it @kadosknight!

**Comment by ficsorr** [comment]
Hi, I would like to start with the 'Forms' page.

**Comment by balazsorban44** [comment]
It's yours @ficsorr!

**Comment by balazsorban44** [comment]
Taking `Conditional Rendering` page.

**Comment by balazsorban44** [comment]
Taking `List and Keys` page.

**Comment by balazsorban44** [comment]
Taking `Composition vs Inheritance` page.

**Comment by balazsorban44** [comment]
Taking `Glossary` page.

**Comment by balazsorban44** [comment]
Taking `Lifting State Up`

**Comment by benkeakos** [comment]
I would like to start with Thinking in React page.

**Comment by gergely-nagy** [comment]
It's yours @benkeakos !

**Comment by balazsorban44** [comment]
@kadosknight @ficsorr @benkeakos any progress? 🙂

**Comment by balazsorban44** [comment]
Taking `React` from API Reference

**Comment by gergely-nagy** [comment]
The following pages have been unclaimed due to inactivity. Everyone else are now free to claim these pages for translation once again.

### Basics

- [ ] Handling Events
- [ ] Forms
- [ ] Thinking in React

**Comment by gergely-nagy** [comment]
I'm taking `Fragments` as a next one.

**Comment by gergely-nagy** [comment]
Taking ` CDN Links` .

**Comment by balazsorban44** [comment]
@gergely-nagy you are on 🔥😄💪

**Comment by punkah** [comment]
Hi guys,
I have started translating the Getting Started page, can you add me to the list?
I will continue with the next item from the 'Core' section after this,

Thanks!

**Comment by balazsorban44** [comment]
@punkah tell us if you need help with anything :smile:

**Comment by n3ko** [comment]
I would like to claim the "Thinking in React" section

**Comment by punkah** [comment]
Taking `Basics/Handling Events`

**Comment by dzsi1994** [comment]
Takin `APIs and AJAX`

**Comment by punkah** [comment]
Taking `Basics/Forms`

**Comment by balazsorban44** [comment]
Great news 🎉 folks, by merging #30, the site is now crawled by Algolia, and the search bar works for Hungarian 🇭🇺

![image](https://user-images.githubusercontent.com/18369201/75435723-c2962980-5953-11ea-9a0a-1741be3036b7.png)

**Comment by punkah** [comment]
Taking `API/React.Component`

**Comment by balazsorban44** [comment]
Taking `API/ReactDOM`

**Comment by balazsorban44** [comment]
Taking `API/ReactDOMServer`

**Comment by balazsorban44** [comment]
Taking `API/JS Environment Requirements`

**Comment by balazsorban44** [comment]
Taking `Installation/Create a New React App`

**Comment by balazsorban44** [comment]
Taking `Installation/Add React to a Website`

**Comment by balazsorban44** [comment]
@dzsi1994 Everything is okay? Do you need any help?

**Comment by balazsorban44** [comment]
Taking all `src/components` (they contain very little text, so it is hanging very low...)

**Comment by balazsorban44** [comment]
Taking `Hooks/Introducing Hooks`

**Comment by gergely-nagy** [comment]
Really nice progress, @balazsorban44 ! Keep it up 👍

**Comment by balazsorban44** [comment]
Taking `API/SyntheticEvent`

**Comment by balazsorban44** [comment]
Taking `API/DOM Elements`

**Comment by balazsorban44** [comment]
Taking `API/Shallow Renderer`

**Comment by balazsorban44** [comment]
Taking `API/Test Renderer`

**Comment by balazsorban44** [comment]
https://hu.reactjs.org/ 🎉

**Comment by balazsorban44** [comment]
Taking `Hooks at a Glance`

**Comment by balazsorban44** [comment]
Taking `Rules of Hooks`

**Comment by balazsorban44** [comment]
Taking `Building Your Own Hooks`

**Comment by punkah** [comment]
Taking `Using the State Hook`

**Comment by punkah** [comment]
Taking `Using the Effect Hook`

**Comment by gergely-nagy** [comment]
Taking Advanced Guides/Typechecking With PropTypes

**Comment by punkah** [comment]
Taking `Advanced Guides/Accessibility`

**Comment by attilaking** [comment]
Hi guys, can I take Hooks API Reference? Haven't written in Hungarian in a while, but will give it a go!

**Comment by balazsorban44** [comment]
@attilaking Thanks for the interest! Yes, you are welcome to take it!

Although, be aware of this https://github.com/reactjs/reactjs.org/issues/3308

**Comment by RichardOtvos** [comment]
Hey guys! I'd like to help, is it okay if I take the `React Without JSX` chapter?

**Comment by balazsorban44** [comment]
@RichardOtvos it's yours :)

**Comment by RichardOtvos** [comment]
@balazsorban44 Created the PR ( #92 ), just comment on it if I should change anything

**Comment by silver-snoopy** [comment]
@balazsorban44 I would like to help with the translation process. The repo seems a little bit behind of the English version.
How can I help? 😺

**Comment by balazsorban44** [comment]
Hi @silver-snoopy, and thanks for the interest! The React docs is getting a big overhaul as I understood from https://github.com/reactjs/reactjs.org/issues/3308 and it is said that the content will be completely rewritten (https://github.com/reactjs/reactjs.org/issues/3308#issuecomment-706765477). This is the main reason I did not give this project as much attention as before. That said, the current format is hopefully still useful for many, and I still hope that the already translated content can help us in some way when translating the new content as well.

So if you would like to help out, I suggest you take one item at a time from the first comment of this issue and create PRs. I am happy to review them :slightly_smiling_face:

**Comment by balazsorban44** [comment]
I just cleaned up fixed/merged the open PRs, we are down to 0 again 🙂 It's easier for me to maintain as well if someone shows interest in helping out ❤

**Comment by silver-snoopy** [comment]
Thanks @balazsorban44 - Then I will look around 😉

**Comment by balazsorban44** [comment]
For anyone following, there is new information available! It looks like translations can be resumed:

https://github.com/reactjs/reactjs.org/issues/4135

Please reach out to me if you are interested.

**Comment by fulopkovacs** [comment]
> For anyone following, there is new information available! It looks like translations can be resumed:
> 
> [reactjs/react.dev#4135](https://github.com/reactjs/react.dev/issues/4135)
> 
> Please reach out to me if you are interested.

The new react beta docs are really good, they absolutely deserve to be translated! I am interested in this project, can we talk about it? Should I reach out on Twitter? (https://twitter.com/notacheetah)  ☺️

**Comment by gaearon** [comment]
Hi folks,

Just a heads-up that we've done our best to bring `main` and `legacy` branches up-to-date with upstream. This brings you to the latest visual design and sets up all the redirects. We don't anticipate more changes necessary on `legacy`. For `main`, there's a few things you need to be aware of:

- Keep in mind translating UI is best done closer to the end. We plan to make non-trivial code changes to the repo over the next few months. So it's best to focus on the content rather than on UI components.
- The homepage is untranslated so ideally it would be good if you could do a pass at that. For now, unfortunately it requires messing with the code file.

Thank you so much for your cooperation!

**Comment by gaearon** [comment]
Thanks to everyone who contributed to the old website translation.
Started a new issue for the new website translation: https://github.com/reactjs/hu.react.dev/issues/219
